export default {
  login: "pramodui5",
  id: 12524071,
  node_id: "MDQ6VXNlcjEyNTI0MDcx",
  avatar_url: "https://avatars.githubusercontent.com/u/12524071?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/pramodui5",
  html_url: "https://github.com/pramodui5",
  followers_url: "https://api.github.com/users/pramodui5/followers",
  following_url: "https://api.github.com/users/pramodui5/following{/other_user}",
  gists_url: "https://api.github.com/users/pramodui5/gists{/gist_id}",
  starred_url: "https://api.github.com/users/pramodui5/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/pramodui5/subscriptions",
  organizations_url: "https://api.github.com/users/pramodui5/orgs",
  repos_url: "https://api.github.com/users/pramodui5/repos",
  events_url: "https://api.github.com/users/pramodui5/events{/privacy}",
  received_events_url: "https://api.github.com/users/pramodui5/received_events",
  type: "User",
  site_admin: false,
  name: "Pramod Kumar Bhoi",
  company: "Extentia Information Technology",
  blog: "",
  location: "Pune",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 19,
  public_gists: 20,
  followers: 350,
  following: 200,
  created_at: "2015-05-20T06:04:57Z",
  updated_at: "2022-11-11T06:06:41Z"
};
